name: Flutter

on:
  push:
    branches:
      - release
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download assets
        run: |
          rm -r assets
          wget ${{ secrets.ASSETS_LINK }}
          tar -xf assets.tbz2
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Analyze project
        run: flutter analyze --no-fatal-warnings
      
  build-android:
    needs: [analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read secrets
        run: |
          echo "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 -d > android/key.properties
          echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
      - name: Download assets
        run: |
          rm -r assets
          wget ${{ secrets.ASSETS_LINK }}
          tar -xf assets.tar.bz2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk
          flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: enekeskonyv-release.apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.github.reformatus.enekeskonyv
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          track: production
          status: draft
          changesNotSentForReview: true
